---
- name: Deploy Docker container on Production Server
  hosts: all
  become: yes

  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install Docker if not present
      apt:
        name: docker.io
        state: present

    - name: Run Docker container from Docker Hub image
      docker_container:
        name: devops-app
        image: uperve300/devops-app:latest
        state: started
        restart_policy: always
        ports:
          - "80:3000"
